kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: guestbook-app
  name: redis-slave-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: faster
  resources:
    requests:
      storage: 4Gi
